# Generated by Django 5.1.1 on 2024-09-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='number_of_pages',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of pages'),
        ),
    ]
