# Generated by Django 5.1.1 on 2024-09-10 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_libraryuser_account_creation_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryuser',
            name='account_creation_time',
        ),
    ]
