# Generated by Django 5.1.1 on 2024-09-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
